#!/bin/bash -ex

if [[ $USER == "root" ]]; then
	echo "Do no run in root mode. Exit sudo please."
	exit 1
fi

echo "Installing source hook on profile and rc..."
if [[ `grep dotfiles ~/.bashrc` == "" ]]; then
  PATH="$PATH:~/.dotfiles/bin"
  append_text "source ~/.dotfiles/load.sh" ~/.bashrc
  append_text "source ~/.dotfiles/load.sh" ~/.bash_profile
fi

# Run the install (I'd like to pull this out of rake, eventually)
if which rake && [ ! -f ~/.dotfiles_installed ]; then
  echo "Installing dotfiles..."
  cd ~/.dotfiles/
  rake install && touch ~/.dotfiles_installed
else
  echo "Warning: No rake detected. Deferring installation."
fi
