#!/bin/bash
# TODO: set "~/.gemrc" into a bash var but it did'nt work last time.
echo "# DO NOT EDIT THIS FILE. Edit .dotfiles/gem/gemrc.base" > ~/.gemrc
cat ~/.dotfiles/gem/gemrc.base >> ~/.gemrc
if [[ -f ~/.gemrc.local ]]; then
  # TODO: add a \n at the echo and not a new echo line, but it didn't work either
  echo "" >> ~/.gemrc
  echo "# Local gemrc copied from ~/.gemrc.local" >> ~/.gemrc
  cat ~/.gemrc.local >> ~/.gemrc
fi
