#!/bin/bash
echo "# DO NOT EDIT THIS FILE. \n# Edit .dotfiles/gem/gemrc.base" > ~/.gemrc
cat ~/.dotfiles/gem/gemrc.base >> ~/.gemrc
if [[ -f ~/.gemrc.local ]]; then
  echo "\n# Local gemrc copied from ~/.gemrc.local" >> ~/.gemrc
  cat ~/.gemrc.local >> ~/.gemrc
fi
